# Generated by Django 4.2.3 on 2023-07-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_city_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='id',
            field=models.CharField(default=0, max_length=20, primary_key=True, serialize=False),
        ),
    ]
